<template>
  <div
    class="min-h-screen bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 text-gray-800 overflow-hidden"
  >
    <div class="absolute inset-0 bg-grid-pattern opacity-10"></div>

    <main class="relative container mx-auto px-4 py-24">
      <div class="text-center max-w-4xl mx-auto">
        <h1
          class="text-6xl sm:text-7xl font-extrabold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 animate-fadeIn"
        >
          Customized Hypnosis For Your Needs
        </h1>
        <p
          class="text-2xl mb-12 text-gray-600 animate-fadeIn animation-delay-300"
        >
          AI-powered hypnosis that is voiced and customized for your personal
          adventure.
        </p>
        <div
          class="flex justify-center space-x-4 animate-fadeIn animation-delay-600"
        >
          <BaseButton
            text="Get Started"
            class="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white"
          />
          <BaseButton
            text="Learn More"
            class="bg-white text-indigo-600 hover:bg-indigo-50"
          />
        </div>
      </div>
    </main>

    <section
      class="py-24 px-4 bg-white bg-opacity-70 backdrop-filter backdrop-blur-lg"
    >
      <h2 class="text-4xl font-bold mb-16 text-center text-indigo-800">
        Key Features
      </h2>
      <div class="flex flex-wrap justify-center gap-12">
        <div
          v-for="feature in features"
          :key="feature.title"
          class="bg-white bg-opacity-50 p-8 rounded-2xl shadow-lg max-w-sm transform hover:scale-105 transition-all duration-300"
        >
          <h3 class="text-2xl font-semibold mb-4 text-indigo-600">
            {{ feature.title }}
          </h3>
          <p class="text-gray-600">{{ feature.description }}</p>
        </div>
      </div>
    </section>

    <section
      class="py-24 px-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white"
    >
      <h2 class="text-4xl font-bold mb-16 text-center">What Our Users Say</h2>
      <div class="flex flex-wrap justify-center gap-12">
        <div
          v-for="testimonial in testimonials"
          :key="testimonial.name"
          class="bg-white bg-opacity-10 p-8 rounded-2xl backdrop-filter backdrop-blur-lg max-w-sm"
        >
          <p class="italic mb-6 text-lg">"{{ testimonial.quote }}"</p>
          <div class="flex items-center">
            <img
              :src="testimonial.avatar"
              :alt="testimonial.name"
              class="w-16 h-16 rounded-full mr-4 border-2 border-white"
            />
            <div>
              <p class="font-semibold">{{ testimonial.name }}</p>
              <p class="text-sm text-indigo-200">{{ testimonial.title }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <LandingJourney />

    <footer class="bg-indigo-900 text-white py-8 px-6 text-center">
      <p>&copy; 2024 HypnoAI. All rights reserved.</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";

onMounted(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("animate-fadeIn");
        }
      });
    },
    { threshold: 0.1 },
  );

  document.querySelectorAll("section").forEach((section) => {
    observer.observe(section);
  });
});

const features = [
  {
    title: "AI-Powered Scripts",
    description:
      "Unique hypnosis scripts generated by advanced AI algorithms tailored to your specific needs.",
  },
  {
    title: "Voice Customization",
    description:
      "Choose from a variety of AI voices or use your own recording for a personalized experience.",
  },
  {
    title: "Flexible Sessions",
    description:
      "Create sessions of various lengths to fit your schedule and preferences.",
  },
];
const testimonials = [
  {
    quote:
      "HypnoAI has transformed my relaxation routine. The personalized sessions are incredibly effective!",
    name: "Sarah Johnson",
    title: "Yoga Instructor",
    avatar: "https://100k-faces.glitch.me/random-image",
  },
  {
    quote:
      "I was skeptical at first, but the AI-generated scripts are surprisingly insightful and helpful.",
    name: "Michael Chen",
    title: "Software Engineer",
    avatar: "https://100k-faces.glitch.me/random-image",
  },
  {
    quote:
      "The voice customization feature makes each session feel uniquely tailored to me. Highly recommend!",
    name: "Emma Rodriguez",
    title: "Wellness Coach",
    avatar: "https://100k-faces.glitch.me/random-image",
  },
];
</script>

<style>
.bg-grid-pattern {
  background-image: linear-gradient(
      to right,
      rgba(99, 102, 241, 0.1) 1px,
      transparent 1px
    ),
    linear-gradient(to bottom, rgba(99, 102, 241, 0.1) 1px, transparent 1px);
  background-size: 40px 40px;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fadeIn {
  animation: fadeIn 1s ease-out forwards;
}

.animation-delay-300 {
  animation-delay: 300ms;
}

.animation-delay-600 {
  animation-delay: 600ms;
}

#mind-map {
  opacity: 0.2;
  transition: opacity 0.3s ease-in-out;
}

#mind-map:hover {
  opacity: 0.6;
}
</style>
