<script setup lang="ts">
const features = [
  {
    title: "AI-Powered Scripts",
    description:
      "Unique hypnosis scripts generated by advanced AI algorithms tailored to your specific needs.",
  },
  {
    title: "Voice Customization",
    description:
      "Choose from a variety of AI voices or use your own recording for a personalized experience.",
  },
  {
    title: "Flexible Sessions",
    description:
      "Create sessions of various lengths to fit your schedule and preferences.",
  },
];
</script>

<template>
  <section
    class="py-24 px-4 bg-white bg-opacity-70 backdrop-filter backdrop-blur-lg"
  >
    <h2 class="text-4xl font-bold mb-16 text-center text-indigo-800">
      Key Features
    </h2>
    <div class="flex flex-wrap justify-center gap-12">
      <div
        v-for="feature in features"
        :key="feature.title"
        class="bg-white bg-opacity-50 p-8 rounded-2xl shadow-lg max-w-sm transform hover:scale-105 transition-all duration-300"
      >
        <h3 class="text-2xl font-semibold mb-4 text-indigo-600">
          {{ feature.title }}
        </h3>
        <p class="text-gray-600">{{ feature.description }}</p>
      </div>
    </div>
  </section>
</template>
